{
  "uid" : "6e1d090fae51f179",
  "name" : "test_failed",
  "fullName" : "test_allure_feature.TestLogin#test_failed",
  "historyId" : "56e28a553a69b2e3266453d935c13e67",
  "time" : {
    "start" : 1582701229473,
    "stop" : 1582701229473,
    "duration" : 0
  },
  "description" : "这是一个一直执行失败的测试用例",
  "descriptionHtml" : "<p>这是一个一直执行失败的测试用例</p>\n",
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'attach.png'",
  "statusTrace" : "self = <test_allure_feature.TestLogin object at 0x0000026E922F7550>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.story(\"测试失败用例与用例中添加附件\")\n    @allure.link(\"https://www.cnblogs.com/linuxchao/\", name=\"bug链接\")\n    @allure.description(\"这是一个一直执行失败的测试用例\")\n    def test_failed(self):\n        \"\"\"你也可以在这里添加用例的描述信息，但是会被allure.description覆盖\"\"\"\n        try:\n>           assert False\nE           AssertionError: assert False\n\ntest_allure_feature.py:152: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_allure_feature.TestLogin object at 0x0000026E922F7550>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.story(\"测试失败用例与用例中添加附件\")\n    @allure.link(\"https://www.cnblogs.com/linuxchao/\", name=\"bug链接\")\n    @allure.description(\"这是一个一直执行失败的测试用例\")\n    def test_failed(self):\n        \"\"\"你也可以在这里添加用例的描述信息，但是会被allure.description覆盖\"\"\"\n        try:\n            assert False\n        except AssertionError as e:\n>           with open(\"attach.png\", \"rb\") as f:\nE           FileNotFoundError: [Errno 2] No such file or directory: 'attach.png'\n\ntest_allure_feature.py:154: FileNotFoundError",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "story",
    "value" : "测试失败用例与用例中添加附件"
  }, {
    "name" : "feature",
    "value" : "登录模块"
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "suite",
    "value" : "test_allure_feature"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-1TP29R9"
  }, {
    "name" : "thread",
    "value" : "14420-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_allure_feature"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ {
    "name" : "bug链接",
    "url" : "https://www.cnblogs.com/linuxchao/",
    "type" : "link"
  } ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "6e1d090fae51f179.json",
  "parameterValues" : [ ]
}