{"name": "test_failed", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'attach.png'", "trace": "self = <test_allure_feature.TestLogin object at 0x0000026E922F7550>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.story(\"测试失败用例与用例中添加附件\")\n    @allure.link(\"https://www.cnblogs.com/linuxchao/\", name=\"bug链接\")\n    @allure.description(\"这是一个一直执行失败的测试用例\")\n    def test_failed(self):\n        \"\"\"你也可以在这里添加用例的描述信息，但是会被allure.description覆盖\"\"\"\n        try:\n>           assert False\nE           AssertionError: assert False\n\ntest_allure_feature.py:152: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_allure_feature.TestLogin object at 0x0000026E922F7550>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.story(\"测试失败用例与用例中添加附件\")\n    @allure.link(\"https://www.cnblogs.com/linuxchao/\", name=\"bug链接\")\n    @allure.description(\"这是一个一直执行失败的测试用例\")\n    def test_failed(self):\n        \"\"\"你也可以在这里添加用例的描述信息，但是会被allure.description覆盖\"\"\"\n        try:\n            assert False\n        except AssertionError as e:\n>           with open(\"attach.png\", \"rb\") as f:\nE           FileNotFoundError: [Errno 2] No such file or directory: 'attach.png'\n\ntest_allure_feature.py:154: FileNotFoundError"}, "description": "这是一个一直执行失败的测试用例", "start": 1582701229473, "stop": 1582701229473, "uuid": "9a559a5e-2799-4aae-9485-d59013bce17b", "historyId": "56e28a553a69b2e3266453d935c13e67", "testCaseId": "1a0ad6928dd166fb09d3c788ed812d70", "fullName": "test_allure_feature.TestLogin#test_failed", "labels": [{"name": "story", "value": "测试失败用例与用例中添加附件"}, {"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "normal"}, {"name": "suite", "value": "test_allure_feature"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-1TP29R9"}, {"name": "thread", "value": "14420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_feature"}], "links": [{"type": "link", "url": "https://www.cnblogs.com/linuxchao/", "name": "bug链接"}]}